name: TheTowersRemastered
version: 1.3
api-version: 1.16
main: me.PauMAVA.TTR.TTRCore

commands:
  ttrstart:
    description: Start the match
  ttrenable:
    description: Enbles the plugin on server start.
  ttrdisable:
    description: Disables the plugin on server start.